# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@stable-kf6'
    'frameworks/kconfigwidgets': '@stable-kf6'
    'frameworks/kcoreaddons': '@stable-kf6'
    'frameworks/kcrash': '@stable-kf6'
    'frameworks/ki18n': '@stable-kf6'
    'frameworks/kwidgetsaddons': '@stable-kf6'
    'frameworks/kio': '@stable-kf6'
    'frameworks/purpose': '@stable-kf6'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
