# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/kconfigwidgets': '@same'
    'frameworks/kcoreaddons': '@same'
    'frameworks/ki18n': '@same'
    'frameworks/kwidgetsaddons': '@same'
    'frameworks/kio': '@same'
    'frameworks/purpose': '@same'
