# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/kconfigwidgets': '@same'
    'frameworks/kcoreaddons': '@same'
    'frameworks/ki18n': '@same'
    'frameworks/kwidgetsaddons': '@same'
    'frameworks/kio': '@same'
    'frameworks/purpose': '@same'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/purpose': '@latest-kf6'
